global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Machine stats
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Docker stats
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  # Home Assistant
  - job_name: hass
    scrape_interval: 60s
    metrics_path: /api/prometheus

    authorization:
      credentials: "" # Nahraďte long-time tokenem vygenerovaným z HA

    static_configs:
      - targets: ['localhost:8123']#      