
version: '3'

volumes:
  nginxproxymanager-data:
    driver: local  
  nginxproxymanager-ssl:
    driver: local  

services:

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "mariadb" # je potreba pridat MySQL/MariaDb container
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nginxproxymanager-data:/data # jednotlive konfigurace
      - nginxproxymanager-ssl:/etc/letsencrypt # vygenerovane certifikaty
    restart: always
