version: '3'

volumes:
  portainer-data:
    driver: local
    
services:

  portainer:  
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always