# Web: https://github.com/prometheus/node_exporter
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - '/:/host:ro'
    network_mode: host     
    pid: host  
    restart: unless-stopped 
    command:
      - '--path.rootfs=/host'      